#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.env.vercel"
DEPLOY_ENV="$ROOT/.env.deploy"

jwt_secret="$(openssl rand -base64 32)"
jwt_refresh_secret="$(openssl rand -base64 32)"
media_signing_secret="$(openssl rand -base64 32)"

database_url=""
redis_url=""
site_url="https://gamified-video-platform.vercel.app"

if [[ -f "$DEPLOY_ENV" ]]; then
  # shellcheck disable=SC1090
  set -a && source "$DEPLOY_ENV" && set +a
fi

database_url="${DATABASE_URL:-$database_url}"
redis_url="${REDIS_URL:-$redis_url}"
site_url="${NEXT_PUBLIC_SITE_URL:-$site_url}"

if [[ -z "$database_url" || -z "$redis_url" ]]; then
  cat >&2 <<'EOF'
Missing DATABASE_URL or REDIS_URL.

Create .env.deploy (gitignored) with:

  DATABASE_URL=postgresql://...
  REDIS_URL=rediss://...

Then run: npm run env:vercel
EOF
  exit 1
fi

if [[ "$redis_url" == redis://* ]]; then
  redis_url="rediss://${redis_url#redis://}"
fi

cat >"$OUT" <<EOF
# Generated by scripts/prepare-vercel-env.sh — import this file in Vercel (Production).
# Do not commit. Regenerate secrets: npm run env:vercel

DATABASE_URL=$database_url
REDIS_URL=$redis_url
JWT_SECRET=$jwt_secret
JWT_REFRESH_SECRET=$jwt_refresh_secret
MEDIA_SIGNING_SECRET=$media_signing_secret
MEDIA_TOKEN_TTL_SEC=120
NEXT_PUBLIC_SITE_URL=$site_url
PLATFORM_VERTICAL=ADULT
PLATFORM_AGE_GATE=true
ADS_ENABLED=false
EOF

echo "Wrote $OUT ($(wc -l <"$OUT" | tr -d ' ') vars). Import it in Vercel → Environment Variables → Import .env"
